### PR TITLE
HTTP API

### PR DESCRIPTION
**Pull request by mrosseel**
please comment on usage of asciidoc, style, content, ... .
It's fairly minimal, let me know what you feel is missing, maybe interaction examples for certain trades?

### CODE REVIEW

**Comment by cbeams** [comment]
Thanks Mike. Yes, it would be good to have at least one worked example in the doc. Something from the perspective of an application using the API, e.g. something that periodically queries available offers, takes an offer that meets a given criteria, etc, and what API calls it makes at each step in the process. The "simplest possible Bisq trading bot" would be a good start.

Regarding naming, please rename this doc from `Bisq1.adoc` to `http-api.adoc`. I'd like to see if we can get away with referring to our proposals by a short, intuitive identifier rather than by number. This identifier can also map into Slack as the channel name, e.g. `#http-api`.

Regarding style, please:
 - [capitalize the subject line of commit messages](https://chris.beams.io/posts/git-commit/#capitalize); and
 - [sign your commits](https://github.com/bisq-network/docs/blob/master/CONTRIBUTING.adoc#sign-commits-with-gpg)

Also, you mention that the project would be a "separate module", but it is probably better to call it out as being a "separate repository" (I think this is what you actually meant), as well as where that canonical repository would reside, e.g. https://github.com/bisq-network/http-api.

**Comment by cbeams** [comment]
Note that I've retitled the pull request from "first draft of api proposal" to "HTTP API", given that all pull requests to this repository are for proposals (so it need not be repeated), and because any given pull request may go through a number of drafts / revisions before being merged, so there's no need to mention "first draft" in the title.

**Comment by cbeams** [comment]
Perhaps you already noticed this, @mrosseel, but the email address you're using in your Git author metadata doesn't match the address you're using to sign your commits:

```
commit 452af71d75b27cba5b75f47eda090737d6601409 (mrosseel/api-proposal)
gpg: Signature made Thu Sep 14 11:42:05 2017 CEST
gpg:                using RSA key 1D9920AF2A8E6BF0
gpg: Good signature from "Mike Rosseel <mike.rosseel@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 237E C544 40C7 E2CD 84AD  6DCC 1D99 20AF 2A8E 6BF0
Author: Mike Rosseel <mike@eon-consult.be>
Date:   Thu Sep 14 11:40:54 2017 +0200

    Rename proposal

    This proposal will be renamed to http-api, because it better describes
    the contents of the file, and because numbers will either not be used
    or at the very least are not known before a proposal is approved.
```

image

**Comment by mrosseel** [comment]
hi @cbeams yes this was a first test commit, will look into either adding the email to the gpg signature or changing the github email.

**Comment by cbeams** [comment]
Note: I've just created the #http-api channel in Slack, where Mike and I are now discussing next steps with this proposal.

**Comment by cbeams** [comment]
I'm closing this proposal PR per my comments at https://github.com/bisq-network/docs/pull/36#issuecomment-381151939. @mrosseel and I discussed this briefly earlier today as well. Thanks, Mike, for putting together an early cut at a proposal doc. Our use of this repository has evolved quite a bit and we'll see about keeping it issues-only from here out, as that seems to an effective approach.

**Pull request closed without merging**
